### ISSUE TITLE
🐛 Bug: should-semantic-release still isn't blocking releases

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#194]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

[should-semantic-release](https://github.com/JoshuaKGoldberg/should-semantic-release) should be stopping semantic releases on commits that are only chores/docs.

### Actual

Consider ccf602cc1a9a61bda925ce6e4c188ed18399a66f's [release job](https://github.com/JoshuaKGoldberg/template-typescript-node-package/actions/runs/3969289855/jobs/6803582404):

```plaintext
Changelog:
* chore: add --verbose to should-semantic-release (ccf602c)
- if ! npx should-semantic-release --verbose ; then exit 1 ; fi
✔ if ! npx should-semantic-release --verbose ; then exit 1 ; fi
- npm version
✔ npm version
```

A version bump still happened. 😬 

I tried adding `--verbose` in 8219825 and now the [updated release job]()https://github.com/JoshuaKGoldberg/template-typescript-node-package/actions/runs/4098826501/jobs/7068213748) errors:

```plaintext
Changelog:
* chore: release-it --verbose (8219825)
$ if ! npx should-semantic-release --verbose ; then exit 1 ; fi
ERROR Error
    at file:///home/runner/work/template-typescript-node-package/template-typescript-node-package/node_modules/.pnpm/release-it@15.6.0/node_modules/release-it/lib/shell.js:64:18
    at /home/runner/work/template-typescript-node-package/template-typescript-node-package/node_modules/.pnpm/shelljs@0.8.5/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:[10](https://github.com/JoshuaKGoldberg/template-typescript-node-package/actions/runs/4098826501/jobs/7068213748#step:9:11)91:[16](https://github.com/JoshuaKGoldberg/template-typescript-node-package/actions/runs/4098826501/jobs/7068213748#step:9:17))
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by JoshuaKGoldberg** [comment]
Resolved by b8241f3a338a6291c1b650568d433c864610329e.
