### ISSUE TITLE
🐛 Bug: npx fails in setup.js

### ISSUE THREAD

**Issue by jsjoeio** [JoshuaKGoldberg/template-typescript-node-package#316]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

`pnpm setup` exits successfully.

### Actual

It fails:

```js
Generating all-contributors table in README.md...
Error: 
    at file:///Users/jp/dev/ens-expire/script/setup.js:184:9
    exit code: 1
    at ChildProcess.<anonymous> (file:///Users/jp/.npm/_npx/721a1717bb84573e/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:322:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)

Removing devDependency packages only used for setup...
✔️ Done.

Looks like there was a problem. Correct it and try again? 😕
```

**Comment by JoshuaKGoldberg** [comment]
Ah, @emday4prez, it's not just you! https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/278#issuecomment-1474177911
