### ISSUE TITLE
🐛 Bug: Support for SSH remote in getDefaultSettings

### ISSUE THREAD

**Issue by navin-moorthy** [JoshuaKGoldberg/template-typescript-node-package#518]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Support these SSH link in `git remote -v` like below example,

```shell
git remote -v

origin	git@github.com:navin-moorthy/node-ts-package.git (fetch)
origin	git@github.com:navin-moorthy/node-ts-package.git (push)
``` 

### Actual

```shell
pnpm run setup

Welcome to the template-typescript-node-package package setup script! 🎉

┌  Let's collect some information to fill out repository details...
🚀 ~ file: defaults.ts:12 ~ getDefaultSettings ~ gitRemoteFetch: {
  command: 'grep fetch',
  escapedCommand: 'grep fetch',
  exitCode: 0,
  stdout: 'origin\tgit@github.com:navin-moorthy/node-ts-package.git (fetch)',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
}
🚀 ~ file: defaults.ts:34 ~ getDefaultSettings ~ remoteFetchMatch: null
│
└  Looks like there was a problem. Correct it and try again? 😕


/Users/navin/Documents/github/node-ts-package/src/shared/defaults.ts:39
		throw new Error("Could not match a fetch remote from git.");
		      ^

Error: Could not match a fetch remote from git.
    at getDefaultSettings (/Users/navin/Documents/github/node-ts-package/src/shared/defaults.ts:39:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getInputValuesAndOctokit (/Users/navin/Documents/github/node-ts-package/src/shared/inputs.ts:47:46)
    at runOrRestore (/Users/navin/Documents/github/node-ts-package/src/shared/runOrRestore.ts:42:31)
    at setup (/Users/navin/Documents/github/node-ts-package/src/setup/setup.ts:5:9)
    at <anonymous> (/Users/navin/Documents/github/node-ts-package/src/setup/index.ts:3:20)
│
■  Do you want to restore the repository to how it was?
│  Yes
│
└  Operation cancelled. Exiting - maybe another time? 👋

``` 

### Additional Info

My Solution:

```ts
import gitRemoteOriginUrl from "git-remote-origin-url";
import gitUrlParse from "git-url-parse";

export async function getDefaultSettings() {
	try {
		const gitRemoteUrl = await gitRemoteOriginUrl();
		const { name, owner } = gitUrlParse(gitRemoteUrl);

		return { defaultOwner: owner, defaultRepository: name };
	} catch {
		logLine();
		logLine(
			chalk.gray(
				"Could not populate default owner and repository. Did not detect a Git repository with an origin. "
			)
		);

		return {
			defaultOwner: "UserName",
			defaultRepository: "my-lovely-repository",
		};
	}
}
```

**Comment by JoshuaKGoldberg** [comment]
Ooh, I didn't know about those packages - they'd be great. Yes please!

I also am questioning why the script throws an error in the first place for failing to parse the output. It returns defaults in `catch` block anyway. Why throw an error now? +1 to your solution not throwing an error.

**Comment by navin-moorthy** [comment]
<img width="780" alt="image" src="https://github.com/JoshuaKGoldberg/template-typescript-node-package/assets/39694575/9e263801-a7fc-4f54-bccb-933264c7943d">

First command is successfull & it did not return, hence continued to the next command & caught in the `if` block.
