### ISSUE TITLE
🐛 Bug: [HttpError]: Not Found in allcontributors action

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#522]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

As of 2cc8a869344ff3c052dd72c84620564486526eae, https://github.com/JoshuaKGoldberg/all-contributors-auto-action should be running in CI to automatically detect common types of allcontributors contributions.

### Actual

The CI job is ❌ failing in some cases, it seems. https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051:

```plaintext
Run JoshuaKGoldberg/all-contributors-auto-action@v0.3.0
file:///home/runner/work/_actions/JoshuaKGoldberg/all-contributors-auto-action/v0.3.0/dist/index.js:12739
						const error = new requestError.RequestError(
						              ^

RequestError [HttpError]: Not Found
    at file:///home/runner/work/_actions/JoshuaKGoldberg/all-contributors-auto-action/v0.3.0/dist/index.js:12739:21
    at processTicksAndRejections (node:internal/process/task_queues:96:[5](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:6))
    at async doesPullAlreadyHaveComment (file:///home/runner/work/_actions/JoshuaKGoldberg/all-contributors-auto-action/v0.3.0/dist/index.js:50038:29)
    at async file:///home/runner/work/_actions/JoshuaKGoldberg/all-contributors-auto-action/v0.3.0/dist/index.js:50232:32 {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/JoshuaKGoldberg/prettier-plugin-curly/issues/110/comments',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Sun, 11 Jun 2023 19:43:25 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=3153[6](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:7)000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': 'repo',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '04C3:[7](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:8)CAB:59E671:BA4553:64[8](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:9)623DC',
      'x-oauth-scopes': 'repo, workflow',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4[9](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:10)70',
      'x-ratelimit-reset': '1686514[10](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:11)7',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '30',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/reference/issues#list-issue-comments'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/JoshuaKGoldberg/prettier-plugin-curly/issues/[11](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:12)0/comments',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.6.0 Node.js/[16](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:17).16.0 (linux; x64)',
      'x-github-api-version': '[20](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:21)[22](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:23)-11-28',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] { path: null },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: [25](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:26)6,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            'api.github.com:4[43](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:44):::::::::::::::::::::': [Buffer [Uint8Array]]
          },
          list: [ 'api.github.com:[44](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/actions/runs/5237197168/jobs/9455218051#step:4:45)3:::::::::::::::::::::' ]
        },
        [Symbol(kCapture)]: false
      },
      hook: [Function: bound bound register]
    }
  }
}
```

I find the URLs referenced there to be interesting. Neither https://api.github.com/repos/JoshuaKGoldberg/prettier-plugin-curly/issues/11 nor https://api.github.com/repos/JoshuaKGoldberg/prettier-plugin-curly/issues/110 exist. What's going on?

### Additional Info

This might be a bug in https://github.com/JoshuaKGoldberg/all-contributors-auto-action and/or https://github.com/JoshuaKGoldberg/all-contributors-for-repository...

**Comment by JoshuaKGoldberg** [comment]
https://github.com/JoshuaKGoldberg/all-contributors-for-repository/blob/f52d832a189ea9b8aecb88cd7621734ce5ba231a/src/collect/collectMergedPulls.ts#L12

_sigh_

```ts
> return await paginate(defaults, async (options) => {
> 	const response = await octokit.request("GET /search/issues", {
> 		...options,
> 		q: "repo:JoshuaKGoldberg/template-typescript-node-package+is:pr+is:merged",
> 	});
> > 	return response.data.items;
> });
```;

**Comment by JoshuaKGoldberg** [comment]
Fixed in https://github.com/JoshuaKGoldberg/all-contributors-for-repository/issues/28 -> https://github.com/JoshuaKGoldberg/all-contributors-for-repository/pull/29 -> [5080848](https://github.com/JoshuaKGoldberg/template-typescript-node-package/commit/5080848723bc86d76bb77b11417028b7c0a55727).
