### ISSUE TITLE
🐛 Bug: Initialization runs before GitHub branch created (RequestError [HttpError]: Branch not found)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#726]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Running `npx template-typescript-node-package --mode -initialize` after `npx template-typescript-node-package --skip-github-api --mode create` should succeed. 

### Actual

```plaintext
Error: Failed initializing GitHub repository
    at withSpinner (file:///Users/josh/.npm/_npx/b39740db704b12a5/node_modules/template-typescript-node-package/lib/shared/cli/spinners.js:16:11)
    at async initializeWithOptions (file:///Users/josh/.npm/_npx/b39740db704b12a5/node_modules/template-typescript-node-package/lib/initialize/initializeWithOptions.js:39:5)
    at async run (file:///Users/josh/.npm/_npx/b39740db704b12a5/node_modules/template-typescript-node-package/lib/initialize/index.js:11:7)
    at async runOrRestore (file:///Users/josh/.npm/_npx/b39740db704b12a5/node_modules/template-typescript-node-package/lib/shared/runOrRestore.js:7:5)
    at async Object.initialize (file:///Users/josh/.npm/_npx/b39740db704b12a5/node_modules/template-typescript-node-package/lib/initialize/index.js:9:10)
    at async bin (file:///Users/josh/.npm/_npx/b39740db704b12a5/node_modules/template-typescript-node-package/lib/bin/index.js:47:10)
    at async file:///Users/josh/.npm/_npx/b39740db704b12a5/node_modules/template-typescript-node-package/bin/index.js:4:20 {
  [cause]: RequestError [HttpError]: Branch not found
      at /Users/josh/.npm/_npx/b39740db704b12a5/node_modules/@octokit/request/dist-node/index.js:112:21
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async requestWithGraphqlErrorHandling (/Users/josh/.npm/_npx/b39740db704b12a5/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
      at async Job.doExecute (/Users/josh/.npm/_npx/b39740db704b12a5/node_modules/bottleneck/light.js:405:18) {
    status: 404,
    response: {
      url: 'https://api.github.com/repos/JoshuaKGoldberg/testing-cta-6/branches/main/protection',
```

### Additional Info

Looks like the script ran before GitHub finished setting up the repo? On re-run I don't experience this. 🤔

**Comment by JoshuaKGoldberg** [comment]
Hasn't happened again. Maybe a transient issue, or separately fixed by something else? 🎉 

Can re-open if it comes up again.
