### ISSUE TITLE
🐛 Bug: Branch protections conflict with release bots

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#81]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Repositories should be able to have a protected `main` branch.

### Actual

From https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/3#issuecomment-1336348353:

> when I protected my main branch I found I couldn't release anymore (possibly because it's trying to update the main branch with dist?): https://github.com/johnnyreilly/easyauth-deeplink/actions/runs/3612405437/jobs/6087493810
>
> - @johnnyreilly

```plaintext
[8:20:16 AM] [semantic-release] [@semantic-release/git] › ℹ  Found 4 file(s) to commit
[8:20:18 AM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/git"
[8:20:18 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags https://github.com/johnnyreilly/easyauth-deeplink HEAD:main
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: 3 of 3 required status checks are expected. Changes must be made through a pull request.        
To https://github.com/johnnyreilly/easyauth-deeplink
 ! [remote rejected] HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/johnnyreilly/easyauth-deeplink'
    at makeError (/home/runner/work/easyauth-deeplink/easyauth-deeplink/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/easyauth-deeplink/easyauth-deeplink/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async push (/home/runner/work/easyauth-deeplink/easyauth-deeplink/node_modules/@semantic-release/git/lib/git.js:51:3)
    at async module.exports (/home/runner/work/easyauth-deeplink/easyauth-deeplink/node_modules/@semantic-release/git/lib/prepare.js:[69](https://github.com/johnnyreilly/easyauth-deeplink/actions/runs/3612405437/jobs/6087493810#step:5:70):5)
    at async prepare (/home/runner/work/easyauth-deeplink/easyauth-deeplink/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (/home/runner/work/easyauth-deeplink/easyauth-deeplink/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/easyauth-deeplink/easyauth-deeplink/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/runner/work/easyauth-deeplink/easyauth-deeplink/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async pluginsConf.<computed> [as prepare] (/home/runner/work/easyauth-deeplink/easyauth-deeplink/node_modules/semantic-release/lib/plugins/index.js:80:11) {
  shortMessage: 'Command failed with exit code 1: git push --tags https://github.com/johnnyreilly/easyauth-deeplink HEAD:main',
  command: 'git push --tags https://github.com/johnnyreilly/easyauth-deeplink HEAD:main',
  escapedCommand: 'git push --tags "https://github.com/johnnyreilly/easyauth-deeplink" "HEAD:main"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/main.        \n' +
    'remote: error: 3 of 3 required status checks are expected. Changes must be made through a pull request.        \n' +
    'To [https://github.com/johnnyreilly/easyauth-deeplink\n](https://github.com/johnnyreilly/easyauth-deeplink/n)' +
    ' ! [remote rejected] HEAD -> main (protected branch hook declined)\n' +
    "error: failed to push some refs to 'https://github.com/johnnyreilly/easyauth-deeplink'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/git'
}
```

### Additional Info

I'll want to add this to the setup script in #77 probably: https://gist.github.com/tiesmaster/ffd4f4a8b4dd2c127516c93af6cc7b46

**Comment by JoshuaKGoldberg** [comment]
Re-opening because it's still an issue 🙃
