### ISSUE TITLE
🛠 Tooling:   An error occurred while running semantic-release: TypeError: assets.map is not a function

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#84]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

```plaintext
[7:18:49 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[7:18:49 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/git"
[7:18:49 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: assets.map is not a function
    at module.exports (/home/runner/work/template-typescript-node-package/template-typescript-node-package/node_modules/.pnpm/@semantic-release+git@10.0.1_semantic-release@19.0.5/node_modules/@semantic-release/git/lib/prepare.js:37:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async prepare (/home/runner/work/template-typescript-node-package/template-typescript-node-package/node_modules/.pnpm/@semantic-release+git@10.0.1_semantic-release@19.0.5/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (/home/runner/work/template-typescript-node-package/template-typescript-node-package/node_modules/.pnpm/semantic-release@19.0.5/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/template-typescript-node-package/template-typescript-node-package/node_modules/.pnpm/semantic-release@19.0.5/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/runner/work/template-typescript-node-package/template-typescript-node-package/node_modules/.pnpm/semantic-release@19.0.5/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async pluginsConf.<computed> [as prepare] (/home/runner/work/template-typescript-node-package/template-typescript-node-package/node_modules/.pnpm/semantic-release@19.0.5/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/runner/work/template-typescript-node-package/template-typescript-node-package/node_modules/.pnpm/semantic-release@19.0.5/node_modules/semantic-release/index.js:193:3)
    at async module.exports (/home/runner/work/template-typescript-node-package/template-typescript-node-package/node_modules/.pnpm/semantic-release@19.0.5/node_modules/semantic-release/index.js:269:22)
    at async module.exports (/home/runner/work/template-typescript-node-package/template-typescript-node-package/node_modules/.pnpm/semantic-release@19.0.5/node_modules/semantic-release/cli.js:55:5) {
  pluginName: '@semantic-release/git'
}
```

### Additional Info

https://github.com/JoshuaKGoldberg/template-typescript-node-package/actions/runs/3632722702/jobs/6128897738

**Comment by JoshuaKGoldberg** [comment]
Ooh, dup of https://github.com/semantic-release/git/issues/280
